name: Deploy Web Server

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-web.yaml'
      - 'src/**'
      - 'api/**'
      - 'web/**'
      - 'runtime/**'
      - 'bun.lock'
      - 'package.json'
    

jobs:
  build-and-deploy:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.3"

      - name: Install Dependencies
        run: bun install

      - name: Build dependencies
        run: bun run build --filter=@rcade/web^...

      - name: Apply Migrations
        run: bun run db:migrate:remote
        working-directory: web
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy
        run: bun run deploy
        working-directory: web
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}